//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSS.CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsCategory
    {
        public int ID { get; set; }
        public string CateforyName { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Images { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public string Link { get; set; }
        public string LinkAffiliate { get; set; }
    }
}
